select count(*) as customer_count from customer1; 
select count(*) as district1_count from district1;
select count(*) as item1_count from item1;
select count(*) as new_orders1_count from new_orders1;
select count(*) as order_line1_count from order_line1;
select count(*) as orders1_count from orders1;
select count(*) as warehouse1_count from warehouse1;
select count(*) as hisotry_count from history1;
select count(*) as stock_count from stock1;
